extrae: changes for RHEL/CentOS 8
Does not work yet due to glibc changes which require code changes
upstream:

sampling-timer.c:135:51: error: dereferencing pointer to incomplete type 'struct ucontext'
  struct sigcontext *sc = (struct sigcontext *) &uc->uc_mcontext;

Signed-off-by: Adrian Reber <areber@redhat.com>